"use client";

import { KeyRound, Pencil, Plus, Power } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { ActionNotice, Button, ConfirmDialog, DataTable, Modal, PageHeader, SearchInput, StatusBadge, type Column } from "@/shared/components";
import type { StaffUser } from "../models/settings";
import { useSettings } from "./SettingsProvider";

export function UsersView() {
  const { users,addUser,updateUser,toggleUser } = useSettings(); const [query,setQuery] = useState(""); const [modal,setModal] = useState<"new"|"edit"|null>(null); const [active,setActive] = useState<StaffUser|null>(null); const [confirm,setConfirm] = useState(false); const [notice,setNotice] = useState(""); const [error,setError] = useState("");
  const rows = useMemo(() => users.filter((item) => [item.name,item.email,item.role,item.status].join(" ").toLowerCase().includes(query.toLowerCase())),[users,query]);
  const columns: Column<StaffUser>[] = [
    { key:"user",header:"Usuario",cell:(row)=><div className="cell-stack"><strong>{row.name}</strong><small>{row.email}</small></div> },
    { key:"role",header:"Rol",cell:(row)=>row.role },{ key:"access",header:"Último acceso",cell:(row)=>row.lastAccess },{ key:"status",header:"Estado",cell:(row)=><StatusBadge status={row.status} /> },
    { key:"actions",header:"Acciones",className:"actions-cell",cell:(row)=><div className="table-actions"><button title="Editar" onClick={()=>{setActive(row);setModal("edit");}}><Pencil size={16}/></button><button title="Restablecer contraseña" onClick={()=>setNotice(`Contraseña temporal generada para ${row.name}: DC-TEMP24`)}><KeyRound size={16}/></button><button className={row.status === "Activo" ? "danger-icon" : ""} title={row.status === "Activo" ? "Desactivar" : "Activar"} onClick={()=>{setActive(row);setConfirm(true);}}><Power size={16}/></button></div> },
  ];
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);const name=String(data.get("name"));const email=String(data.get("email"));const role=String(data.get("role"));if(!name.trim()||!email.includes("@")){setError("Ingresa un nombre y un correo válido.");return;}if(modal==="new"){const password=addUser({name,email,role});setNotice(`Usuario creado. Contraseña temporal: ${password}`);}else if(active){updateUser({...active,name,email,role});setNotice("Usuario actualizado.");}setModal(null);setError("");};
  return <><PageHeader title="Usuarios" description="Cuentas del personal, roles, accesos y bloqueos." actions={<Button onClick={()=>{setActive(null);setError("");setModal("new");}}><Plus size={17}/> Nuevo usuario</Button>}/>{notice&&<ActionNotice message={notice} onClose={()=>setNotice("")}/>}<section className="card patient-search-card"><SearchInput value={query} onChange={setQuery} placeholder="Buscar por nombre, correo, rol o estado..."/><span>{rows.length} usuarios</span></section><section className="card"><DataTable columns={columns} rows={rows}/></section><Modal open={modal!==null} title={modal==="new"?"Crear usuario":"Editar usuario"} description="El acceso es exclusivo para personal autorizado." onClose={()=>setModal(null)}><form className="form-grid" onSubmit={submit}><label className="field full"><span>Nombre completo *</span><input name="name" defaultValue={active?.name}/></label><label className="field full"><span>Correo *</span><input name="email" type="email" defaultValue={active?.email}/></label><label className="field full"><span>Rol *</span><select name="role" defaultValue={active?.role??"Secretaría"}><option>Administrador</option><option>Secretaría</option><option>Odontólogo</option><option>Asistente</option><option>Cajero</option></select></label>{error&&<p className="form-error full">{error}</p>}<div className="modal-form-actions full"><Button variant="ghost" type="button" onClick={()=>setModal(null)}>Cancelar</Button><Button type="submit">Guardar</Button></div></form></Modal><ConfirmDialog open={confirm} title={active?.status==="Activo"?"Desactivar usuario":"Activar usuario"} message={active?.status==="Activo"?`Se impedirá el acceso de ${active?.name}; su historial permanecerá intacto.`:`Se permitirá nuevamente el acceso de ${active?.name}.`} danger={active?.status==="Activo"} confirmLabel={active?.status==="Activo"?"Desactivar":"Activar"} onClose={()=>setConfirm(false)} onConfirm={()=>{if(active)toggleUser(active.id);setConfirm(false);setNotice("Estado del usuario actualizado.");}}/></>;
}
