"use client";

import { useState } from "react";
import { Download, FileText, WalletCards } from "lucide-react";
import { Button, EmptyState, Modal, StatusBadge } from "@/shared/components";
import { AccountItem, mockAccountItems, mockDocuments, mockPayments, PatientDocument } from "../data/account-documents.mock";
import styles from "./patient-portal.module.css";

type Preview = { title: string; subtitle: string; lines: { label: string; value: string }[] };

function DownloadPreview({ preview, onClose, notify }: { preview: Preview | null; onClose: () => void; notify: (message: string) => void }) {
  return <Modal open={Boolean(preview)} title={preview?.title ?? "Vista previa"} description={preview?.subtitle} onClose={onClose} footer={<><Button variant="secondary" onClick={onClose}>Volver</Button><Button onClick={() => { onClose(); notify("Descarga simulada correctamente."); }}><Download size={16} />Confirmar descarga</Button></>}>{preview && <div className={styles.downloadPreview}><p>Vista previa simulada. No se generará ningún archivo real.</p>{preview.lines.map((line) => <div key={line.label}><span>{line.label}</span><strong>{line.value}</strong></div>)}</div>}</Modal>;
}

export function AccountView({ notify }: { notify: (message: string) => void }) {
  const [detail, setDetail] = useState<AccountItem | null>(null);
  const [preview, setPreview] = useState<Preview | null>(null);
  const statement = { title: "Estado de cuenta", subtitle: "Paciente ficticio · septiembre 2026", lines: [{ label: "Saldo actual", value: "Q 450.00" }, { label: "Movimientos registrados", value: "3" }, { label: "Último pago", value: "Q 600.00 · 04 AGO 2026" }, { label: "Estado", value: "Saldo pendiente" }] };
  return <section className={styles.portalView}><div className={styles.viewHead}><div><h1>Estado de cuenta</h1><p>Consulta tus cargos y pagos registrados de forma simulada.</p></div><Button onClick={() => setPreview(statement)}><Download size={16} />Descargar estado</Button></div><section className={styles.balanceHero}><span><WalletCards size={25} /></span><div><p>Saldo actual</p><h2>Q 450.00</h2><small>Próxima fecha relevante: 10 de octubre de 2026</small></div><StatusBadge status="Pendiente" /></section>{mockAccountItems.length === 0 ? <EmptyState title="No tienes movimientos pendientes." /> : <><section className={styles.accountSection}><div className={styles.sectionHeading}><div><h2>Movimientos y cargos</h2><p>Información financiera ficticia, sin pagos reales.</p></div></div>{mockAccountItems.map((item) => <article key={item.id} className={styles.accountRow}><time>{item.date}</time><div><strong>{item.concept}</strong><span>{item.description}</span></div><b>{item.amount}</b><StatusBadge status={item.status} /><button className={styles.linkButton} type="button" onClick={() => setDetail(item)}>Ver detalle</button></article>)}</section><section className={styles.accountSection}><div className={styles.sectionHeading}><div><h2>Pagos realizados</h2><p>Comprobantes simulados disponibles.</p></div></div>{mockPayments.map((item) => <article key={item.id} className={styles.accountRow}><time>{item.date}</time><div><strong>{item.method}</strong><span>{item.receipt}</span></div><b>{item.amount}</b><StatusBadge status={item.status} /><button className={styles.linkButton} type="button" onClick={() => setPreview({ title: `Comprobante ${item.receipt}`, subtitle: "Pago ficticio registrado", lines: [{ label: "Fecha", value: item.date }, { label: "Método", value: item.method }, { label: "Monto", value: item.amount }, { label: "Estado", value: item.status }] })}>Ver comprobante</button></article>)}</section></>}<Modal open={Boolean(detail)} title={detail?.concept ?? "Detalle"} description={detail?.date} onClose={() => setDetail(null)} footer={<Button onClick={() => setDetail(null)}>Cerrar</Button>}>{detail && <div className={styles.detailContent}><StatusBadge status={detail.status} /><p>{detail.description}</p><p className={styles.total}><span>Monto</span><strong>{detail.amount}</strong></p></div>}</Modal><DownloadPreview preview={preview} onClose={() => setPreview(null)} notify={notify} /></section>;
}

export function DocumentsView({ notify }: { notify: (message: string) => void }) {
  const [detail, setDetail] = useState<PatientDocument | null>(null);
  const [preview, setPreview] = useState<Preview | null>(null);
  const openPreview = (item: PatientDocument) => setPreview({ title: item.name, subtitle: `${item.type} · ${item.date}`, lines: [{ label: "Estado", value: item.status }, { label: "Descripción", value: item.description }, { label: "Paciente", value: "María López (ficticio)" }] });
  return <section className={styles.portalView}><div className={styles.viewHead}><div><h1>Documentos</h1><p>Consulta documentos informativos y consentimientos ficticios.</p></div></div>{mockDocuments.length === 0 ? <EmptyState title="No tienes documentos pendientes por revisar." description="No tienes documentos disponibles actualmente." /> : <div className={styles.documentGrid}>{mockDocuments.map((item) => <article key={item.id} className={styles.documentCard}><span><FileText size={23} /></span><div className={styles.cardTop}><small>{item.type}</small><StatusBadge status={item.status} /></div><h2>{item.name}</h2><p>{item.description}</p><time>{item.date}</time><div><button className={styles.linkButton} type="button" onClick={() => setDetail(item)}>Ver documento</button><button className={styles.linkButton} type="button" onClick={() => openPreview(item)}><Download size={15} />Descargar</button></div></article>)}</div>}<Modal open={Boolean(detail)} title={detail?.name ?? "Documento"} description={detail?.type} onClose={() => setDetail(null)} footer={<Button onClick={() => { if (detail) { openPreview(detail); setDetail(null); } }}>Vista previa de descarga</Button>}>{detail && <div className={styles.detailContent}><StatusBadge status={detail.status} /><p>{detail.description}</p><strong>Fecha</strong><span>{detail.date}</span><strong>Tipo</strong><span>{detail.type}</span></div>}</Modal><DownloadPreview preview={preview} onClose={() => setPreview(null)} notify={notify} /></section>;
}
