"use client";

import { useState } from "react";
import { CheckCircle2, ChevronRight, FileText, PauseCircle, PlayCircle, ReceiptText } from "lucide-react";
import { Button, ConfirmDialog, EmptyState, Modal, StatusBadge } from "@/shared/components";
import { BudgetStatus, mockBudgets, mockTreatments, PatientBudget, PatientTreatment } from "../data/treatments-budgets.mock";
import styles from "./patient-portal.module.css";

export function TreatmentsView() {
  const [detail, setDetail] = useState<PatientTreatment | null>(null);
  return <section className={styles.portalView}><div className={styles.viewHead}><div><h1>Tratamientos</h1><p>Consulta el avance de tu atención y los próximos controles.</p></div></div>{mockTreatments.length === 0 ? <EmptyState title="No tienes tratamientos activos actualmente." /> : <div className={styles.treatmentGrid}>{mockTreatments.map((item) => <article key={item.id} className={styles.treatmentCard}><div className={styles.cardTop}><StatusBadge status={item.status} /><span>{item.specialty}</span></div><h2>{item.name}</h2><p>{item.description}</p><dl><div><dt>Profesional</dt><dd>{item.professional}</dd></div><div><dt>Inicio</dt><dd>{item.startedAt}</dd></div><div><dt>Próxima acción</dt><dd>{item.nextAction}</dd></div></dl><div className={styles.progress}><div><strong>Progreso</strong><span>{item.progress}%</span></div><i><b style={{ width: `${item.progress}%` }} /></i></div><button type="button" className={styles.linkButton} onClick={() => setDetail(item)}>Ver detalle <ChevronRight size={16} /></button></article>)}</div>}<Modal open={Boolean(detail)} title={detail?.name ?? "Detalle del tratamiento"} description={detail?.specialty} onClose={() => setDetail(null)} footer={<Button onClick={() => setDetail(null)}>Entendido</Button>}>{detail && <div className={styles.detailContent}><StatusBadge status={detail.status} /><p>{detail.detail}</p><strong>Responsable</strong><span>{detail.professional}</span><strong>Próxima acción</strong><span>{detail.nextAction}</span></div>}</Modal></section>;
}

export function BudgetsView({ notify }: { notify: (message: string) => void }) {
  const [budgets, setBudgets] = useState(mockBudgets);
  const [detail, setDetail] = useState<PatientBudget | null>(null);
  const [rejecting, setRejecting] = useState<PatientBudget | null>(null);
  const update = (id: string, status: BudgetStatus, message: string) => { setBudgets((items) => items.map((item) => item.id === id ? { ...item, status } : item)); setDetail(null); notify(message); };
  return <section className={styles.portalView}><div className={styles.viewHead}><div><h1>Presupuestos</h1><p>Revisa propuestas de tratamiento y su vigencia.</p></div></div>{budgets.length === 0 ? <EmptyState title="No tienes presupuestos pendientes." /> : <div className={styles.budgetList}>{budgets.map((item) => <article key={item.id} className={styles.budgetCard}><div className={styles.budgetIcon}><ReceiptText size={22} /></div><div className={styles.budgetMain}><div className={styles.cardTop}><span>{item.code} · {item.date}</span><StatusBadge status={item.status} /></div><h2>{item.treatment}</h2><p>{item.description}</p><small>Vigente hasta: {item.validUntil}</small></div><div className={styles.budgetActions}><strong>{item.total}</strong><button type="button" className={styles.linkButton} onClick={() => setDetail(item)}>Ver detalle <ChevronRight size={16} /></button>{item.status === "Pendiente" && <div><Button onClick={() => update(item.id, "Aprobado", "Presupuesto aceptado de forma simulada.")}><CheckCircle2 size={16} />Aceptar</Button><Button variant="secondary" onClick={() => setRejecting(item)}><PauseCircle size={16} />Rechazar</Button></div>}</div></article>)}</div>}<Modal open={Boolean(detail)} title={detail ? `Detalle ${detail.code}` : "Detalle de presupuesto"} description={detail?.treatment} onClose={() => setDetail(null)} footer={detail?.status === "Pendiente" ? <Button onClick={() => update(detail.id, "Aprobado", "Presupuesto aceptado de forma simulada.")}>Aceptar presupuesto</Button> : <Button onClick={() => setDetail(null)}>Cerrar</Button>}>{detail && <div className={styles.detailContent}><StatusBadge status={detail.status} /><p>{detail.description}</p><div className={styles.concepts}>{detail.concepts.map((concept) => <p key={concept.name}><span>{concept.name}</span><strong>{concept.amount}</strong></p>)}</div><p className={styles.total}><span>Total estimado</span><strong>{detail.total}</strong></p><small>Vigencia: {detail.validUntil}</small></div>}</Modal><ConfirmDialog open={Boolean(rejecting)} title="¿Rechazar presupuesto?" message="Esta acción solo cambiará el estado durante esta sesión." confirmLabel="Rechazar presupuesto" danger onClose={() => setRejecting(null)} onConfirm={() => { if (rejecting) update(rejecting.id, "Rechazado", "Presupuesto rechazado de forma simulada."); setRejecting(null); }} /></section>;
}
